package me.rolandliedtke.zadanie_jjd.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Activity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Autogenerated ID", example = "1")
    private Long id;

    @Schema(description = "ID of technician", example = "1")
    private Long technician_id;

    @Schema(description = "Description of activity", example = "Lorem ipsum")
    private String description;

    @Schema(description = "Activity duration", example = "10")
    private int duration;

}