package me.rolandliedtke.zadanie_jjd.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Technician {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Autogenerated ID", example = "1")
    private Long id;

    @Schema(description = "LastName of technician", example = "Kowalski")
    private String last_name;

    @Schema(description = "isActive ? 1-true : 0-false", example = "1")
    private boolean isActive = true;
}
